# Generated by Django 2.1.2 on 2019-03-11 19:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_schedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('transport_type', models.CharField(max_length=20)),
                ('date', models.CharField(max_length=20)),
                ('json_identifier', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Booking Record',
                'verbose_name_plural': 'Booking Records',
                'ordering': ('-created_at',),
            },
        ),
    ]
