BILAL_TRAVELS_DATA = {
  "1": "Lahore",
  "38": "Rawalpindi",
  "3": "Faislabad",
  "4": "Multan",
  "36": "Sialkot",
  "76": "Salam",
  "74": "Shikarpur",
  "73": "Moro",
  "72": "Hyderabad",
  "71": "Sukkur",
  "70": "Luckmarwat",
  "69": "Isa Khail",
  "67": "Mansehra",
  "66": "Abbottabad",
  "65": "Sawat",
  "64": "Mardan",
  "77": "Bhalwal",
  "78": "Chistian",
  "79": "Arifwala",
  "90": "Mian Channu",
  "89": "Tarag",
  "88": "Kamar mashani",
  "87": "Kot chandna",
  "86": "Lalamusa",
  "85": "Lodhran",
  "84": "Dunyiapur",
  "83": "Jahaniya",
  "82": "Muredke",
  "81": "Wazirabad",
  "80": "Bahawalnagar",
  "63": "Kohat",
  "62": "Dera Ismail Khan",
  "61": "Buner",
  "46": "Sadiqabad",
  "45": "Mirpur",
  "44": "Kamoke",
  "43": "Sargodha",
  "42": "Joharabad",
  "41": "Kharian",
  "40": "Gujranwala",
  "39": "Peshawar",
  "37": "Daska",
  "33": "Sahiwal",
  "6": "Karachi",
  "47": "Khushab",
  "48": "Murree",
  "60": "Mianwali",
  "59": "Rahim-Yar-Khan",
  "57": "DGKhan",
  "56": "Jatoi",
  "55": "Muzaffargarh",
  "54": "Liaquatpur",
  "53": "KhanPur",
  "52": "Khanewal",
  "51": "Tonsa",
  "50": "Kotaddu",
  "49": "Sanawan",
  "5": "Buhawalpur"
}

PIA_DATA = {
    "KHI": "Karachi - Jinnah Intl. (KHI)",
    "BHV": "Bahawalpur (BHV)",
    "CJL": "Chitral (CJL)",
    "DBA": "Dalbandin (DBA)",
    "DEA": "Dera Ghazi Khan Intl. (DEA)",
    "LYP": "Faisalabad Intl. (LYP)",
    "GIL": "Gilgit (GIL)",
    "GWD": "Gwadar Intl. (GWD)",
    "ISB": "Islamabad Intl. (ISB)",
    "LHE": "Lahore - Allama Iqbal Intl. (LHE)",
    "MJD": "Moenjodaro (MJD)",
    "MUX": "Multan Intl. (MUX)",
    "PJG": "Panjgur (PJG)",
    "PEW": "Peshawar - Bacha Khan Intl. (PEW)",
    "UET": "Quetta Intl. (UET)",
    "RYK": "Rahim Yar Khan - Shaikh Zayed Intl. (RYK)",
    "SKT": "Sialkot Intl. (SKT)",
    "KDU": "Skardu (KDU)",
    "SKZ": "Sukkur (SKZ)",
    "TUK": "Turbat Intl. (TUK)",
    "PZH": "Zhob (PZH)"
}
